export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="z-10 max-w-5xl w-full items-center justify-center font-mono text-sm">
        <h1 className="text-4xl font-bold mb-4">MILLION DOLLAR IDEA2</h1>
        <p className="text-xl mb-8">Build a web application called 'MILLION DOLLAR IDEA2'. Pages needed: Home, Dashboard Requirements: Build a web application called 'MILLION DOLLAR IDEA'. Pages needed: Home, Dashboard. Requirements: I want a super crisp web app that is more like on the gothic side of the UI with a Noir theme, and then the focus of the web app should be to generate billion-dollar ideas. And make sure it works 100%!!, Let's get this bread dawggggg</p>
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
          <h2 className="text-2xl font-semibold mb-4">Welcome!</h2>
          <p>This is your MVP generated by OPS-X. Start collaborating with your team!</p>
        </div>
      </div>
    </main>
  )
}